# Generated by Django 4.1.3 on 2023-04-15 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=20)),
                ('equipment_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Others', max_length=100)),
                ('date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipment_images')),
                ('last_assigned_date', models.DateField(blank=True, null=True)),
                ('allocation_status', models.BooleanField(default=False)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
