# Generated by Django 4.1.3 on 2023-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
