# Generated by Django 4.1.3 on 2023-05-17 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_equipment_equipment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='requested_equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=20, unique=True)),
                ('equipment_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Others', max_length=100)),
                ('date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipment_images')),
            ],
        ),
    ]
