# Generated by Django 4.1.3 on 2023-05-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_allocationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='request_type',
            field=models.CharField(choices=[('ALLOCATION', 'Allocation'), ('DEALLOCATION', 'Deallocation')], default='ALLOCATION', max_length=12),
        ),
    ]
