# Generated by Django 4.1.3 on 2023-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_requested_equipments_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='purchase_receipt',
            field=models.ImageField(default='images/purchase_receipts/default.png', upload_to='images/purchase_receipts'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='images/equipment_images'),
        ),
    ]
