# Generated by Django 4.1.3 on 2023-06-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_equipment_purchase_receipt_alter_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_equipments',
            name='purchase_receipt',
            field=models.ImageField(default='images/purchase_receipts/default.png', upload_to='images/purchase_receipts'),
        ),
        migrations.AlterField(
            model_name='requested_equipments',
            name='image',
            field=models.ImageField(upload_to='images/equipment_images'),
        ),
    ]
