# Generated by Django 4.1.3 on 2023-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_requested_equipments_purchase_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_receipt',
            field=models.ImageField(upload_to='images/purchase_receipts'),
        ),
        migrations.AlterField(
            model_name='requested_equipments',
            name='purchase_receipt',
            field=models.ImageField(upload_to='images/purchase_receipts'),
        ),
    ]
