# Generated by Django 4.1.3 on 2023-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_equipment_purchase_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='equipment_images'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_receipt',
            field=models.ImageField(upload_to='purchase_receipts'),
        ),
        migrations.AlterField(
            model_name='requested_equipments',
            name='image',
            field=models.ImageField(upload_to='equipment_images'),
        ),
        migrations.AlterField(
            model_name='requested_equipments',
            name='purchase_receipt',
            field=models.ImageField(upload_to='purchase_receipts'),
        ),
    ]
