# Generated by Django 4.1.3 on 2023-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_equipment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
