# Generated by Django 4.1.3 on 2023-06-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_customuser_id_alter_customuser_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requested_equipments',
            name='equipment_id',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_email', models.EmailField(max_length=254, unique=True)),
                ('vendor_contact_no', models.CharField(max_length=15)),
                ('vendor_address', models.CharField(blank=True, max_length=100, null=True)),
                ('website_link', models.CharField(blank=True, max_length=100, null=True)),
                ('parts', models.ManyToManyField(to='myapp.part')),
            ],
        ),
    ]
