# Generated by Django 4.1.3 on 2023-06-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_part_remove_equipment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='Vendor', max_length=100),
        ),
    ]
