# Generated by Django 4.1.3 on 2023-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_vendor_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
