# Generated by Django 4.1.3 on 2023-06-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_vendor_vendor_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_contact_no',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_email',
            new_name='email',
        ),
    ]
