# Generated by Django 4.1.3 on 2023-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_vendor_address_vendor_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_name',
            new_name='name',
        ),
    ]
