# Generated by Django 4.1.3 on 2023-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_vendor_name_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
