# Generated by Django 4.1.3 on 2023-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_equipment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='request_type',
            field=models.CharField(choices=[('Allocation', 'Allocation'), ('Deallocation', 'Deallocation')], default='Allocation', max_length=12),
        ),
    ]
