# Generated by Django 4.1.3 on 2023-07-11 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_allocationrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_equipments',
            name='date_of_request',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
